services:
  db:
    image: mysql:8.0
    container_name: mysql-chamadas
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: chamadas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: spring-api-chamadas
    ports:
      - "8443:8443"
    volumes:
      - ./backups:/app/backups
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chamadas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - BACKUP_PATH=/usr/bin/
      - DB_NAME=chamadas
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy